language: csharp

solution: Authentication.sln

sudo: false

branches:
  except:
    - release

branches:
  only:
    - master
    - develop
    - travis

mono:
  - 3.12.0
  - latest
  - weekly

matrix:
  allow_failures:
    - mono: weekly

before_install:
  - if [ -n "$GH_USER" ]; then git config --global github.user ${GH_USER}; fi;
  - if [ -n "$GH_TOKEN" ]; then git config --global github.token ${GH_TOKEN}; fi;

install:
  - nuget restore Authentication.sln
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory target
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory target

script:
  - xbuild /p:Configuration=Release Authentication.sln
  - mono target/OpenCover.4.6.519/tools/OpenCover.Console.exe -target:"./target/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe" -targetargs:"./MiraclAuthenticationTests/bin/Release/MiraclAuthenticationTests.dll" -register:user
